### Dropwizard skeleton configuration file
##
## Do not commit changes that contain credentials or sensitive data!

server:
  rootPath: /api/v1/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2
  adminConnectors:
    - type: https
      port: 8081
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2

logging:
  loggers:
      org.hibernate.SQL: ALL
  appenders:
    - type: console
      threshold: ALL
      target: stdout
    - type: file
      currentLogFilename: logs/core-permissions-api.log
      archivedLogFilenamePattern: logs/core-permissions-api-%d.log.gz
      archivedFileCount: 5
      threshold: ALL
      timeZone: PST

authentication:
  - username: username
    password: password

api:
  endpointUri: https://api.oregonstate.edu/v1/

#
## Example MS SQL configuration
#
#database:
#  driverClass: net.sourceforge.jtds.jdbc.Driver
#  user: username
#  password: password
#  url: jdbc:jtds:sqlserver://db_url:port/db_name
#  properties:
#    hibernate.dialect: org.hibernate.dialect.SQLServerDialect
#  validationQuery: "SELECT 1"
#  removeAbandoned: true
#  initialSize: 2
#  minSize: 1
#  maxSize: 4
