swagger: '2.0'

info:
  description: "This API retrieves CORE permissions information on different users."
  version: "1.0"
  title: "CORE Permissions API"

tags:
- name: "permissions"
  description: "HR, Student, and Finance permissions (1-5)"

schemes:
- "https"

paths:
  /permissions/{osuID}:

    get:
      tags:
      - "permissions"
      summary: "Retrieve permissions for user by OSU ID"
      operationId: "getPermissionsById"
      produces:
      - "application/json"
      parameters:
        - name: "osuID"
          in: "path"
          description: "OSU ID of person whose permissions will be retrieved"
          required: true
          type: "integer"
      responses:
        200:
          description: "Permissions successfully retrieved"
          schema:
            $ref: "#/definitions/PermissionsResult"
        404:
          description: "No user with this OSU ID found"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"

definitions:

  PermissionLevel:
    type: "integer"
    minimum: 1
    maximum: 5

  Permissions:
    type: "object"
    properties:
      HRPermissions:
        $ref: "#/definitions/PermissionLevel"
      StudentPermissions:
        $ref: "#/definitions/PermissionLevel"
      FinancePermissions:
        $ref: "#/definitions/PermissionLevel"

  PermissionsResult:
    type: "object"
    properties:
      links:
        type: "object"
      data:
        type: "object"
        properties:
          id:
            type: "integer"
          type:
            type: "string"
          attributes:
            $ref: "#/definitions/Permissions"

  Error:
    type: "object"
    properties:
      status:
        type: "integer"
      developerMessage:
        type: "string"
      userMessage:
        type: "string"
      code:
        type: "integer"
      details:
        type: "string"
